#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

while read file
do
    fullpath="$(pwd)/$file"
    case "$1" in
        "w")
            ln -f "$fullpath" /home/gerry/.config/wallpaper
            feh --bg-fill ~/.config/wallpaper
            ;;
        "y")      echo -n "$fullpath" | xclip -in -selection clipboard ;;
        "c")      xclip -selection clipboard -target image/png "$file" ;;
        "g")      tr '\n' '\0' | xargs -0 gimp & ;;
        "d")      [ "$(printf "Sí\\nNo" | dmenu -p "Eliminar imatge?")" = "Sí" ] && rm "$file" ;;
        "comma")  rotate 270 ;;
        "period") rotate  90 ;;
        "slash")  rotate 180 ;;
    esac
done
